env:
  browser: true
  commonjs: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
rules: {
  "@typescript-eslint/no-explicit-any": "error",
  "@typescript-eslint/indent": "off" 
}
